version: '3.9'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /mnt/blockstorage:/mnt/blockstorage:ro
      - /opt/nginx_logs:/var/log/nginx

    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  resume-log:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./resume_log:/app
      - /opt/nginx_logs:/opt/nginx_logs:ro   # <-- 新增，映射宿主机的日志目录
    command: >
      sh -c "node server.js"
    expose:
      - "3000"
    networks:
      - app-network
    restart: always


networks:
  app-network:
    driver: bridge
